# Build configuration for HA Add-on
# This allows building from the repo root context

build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"

# Build the Dockerfile from the parent (repo root) directory
# This gives access to all project files
args:
  BUILD_FROM: "{build_from}"

# Specify that the build context is the parent directory
context: ..

# Use the Dockerfile in this (darkstar) folder
dockerfile: darkstar/Dockerfile
