#!/usr/bin/env bash
# Darkstar Energy Manager - Home Assistant Add-on Entrypoint
set -e

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# Read options from HA Add-on config
CONFIG_PATH=/data/options.json

if [ -f "$CONFIG_PATH" ]; then
    TIMEZONE=$(jq -r '.timezone // "Europe/Stockholm"' "$CONFIG_PATH")
    LOG_LEVEL=$(jq -r '.log_level // "info"' "$CONFIG_PATH")
    PRICE_AREA=$(jq -r '.price_area // "SE4"' "$CONFIG_PATH")
    
    # Entity selections from Add-on UI
    BATTERY_SOC=$(jq -r '.battery_soc_sensor // ""' "$CONFIG_PATH")
    PV_SENSOR=$(jq -r '.pv_production_sensor // ""' "$CONFIG_PATH")
    LOAD_SENSOR=$(jq -r '.load_consumption_sensor // ""' "$CONFIG_PATH")
    
    # System profile toggles
    HAS_SOLAR=$(jq -r '.has_solar // true' "$CONFIG_PATH")
    HAS_BATTERY=$(jq -r '.has_battery // true' "$CONFIG_PATH")
    HAS_WATER_HEATER=$(jq -r '.has_water_heater // true' "$CONFIG_PATH")
else
    TIMEZONE="Europe/Stockholm"
    LOG_LEVEL="info"
    PRICE_AREA="SE4"
    BATTERY_SOC=""
    PV_SENSOR=""
    LOAD_SENSOR=""
    HAS_SOLAR="true"
    HAS_BATTERY="true"
    HAS_WATER_HEATER="true"
fi

# Set timezone
export TZ="$TIMEZONE"
export LOG_LEVEL="$LOG_LEVEL"

# Create config directory
mkdir -p /config/darkstar

# =============================================================================
# AUTO-DETECT HA CONNECTION (SUPERVISOR_TOKEN)
# =============================================================================
# When running as HA Add-on, SUPERVISOR_TOKEN is automatically available
# and we can use http://supervisor/core as the HA API endpoint

if [ -n "$SUPERVISOR_TOKEN" ]; then
    log "HA Add-on detected - auto-configuring connection..."
    
    # Generate secrets.yaml with Supervisor token (no manual token needed!)
    cat > /config/darkstar/secrets.yaml << EOF
# Auto-generated by Darkstar HA Add-on
# Using SUPERVISOR_TOKEN for automatic HA authentication
home_assistant:
  url: "http://supervisor/core"
  token: "${SUPERVISOR_TOKEN}"

notifications:
  discord_webhook_url: ""
EOF
    log "Generated secrets.yaml with Supervisor token"
else
    # Standalone mode - copy template if missing
    if [ ! -f /config/darkstar/secrets.yaml ]; then
        cp /app/secrets.example.yaml /config/darkstar/secrets.yaml
        log "Created secrets template at /config/darkstar/secrets.yaml"
        log "Please edit /config/darkstar/secrets.yaml with your HA token!"
    fi
fi

# =============================================================================
# CONFIG.YAML SETUP
# =============================================================================

if [ ! -f /config/darkstar/config.yaml ]; then
    cp /app/config.default.yaml /config/darkstar/config.yaml
    log "Created default config at /config/darkstar/config.yaml"
fi

# Apply Add-on UI settings to config.yaml
python3 << EOF
import yaml
from pathlib import Path
import os

config_path = Path('/config/darkstar/config.yaml')
config = yaml.safe_load(config_path.read_text()) or {}

modified = False

# Apply entity selections from Add-on config
battery_soc = os.environ.get('BATTERY_SOC', '$BATTERY_SOC')
pv_sensor = os.environ.get('PV_SENSOR', '$PV_SENSOR')
load_sensor = os.environ.get('LOAD_SENSOR', '$LOAD_SENSOR')
price_area = os.environ.get('PRICE_AREA', '$PRICE_AREA')
has_solar = '$HAS_SOLAR'.lower() == 'true'
has_battery = '$HAS_BATTERY'.lower() == 'true'
has_water_heater = '$HAS_WATER_HEATER'.lower() == 'true'

# Update price area
if price_area:
    if 'nordpool' not in config:
        config['nordpool'] = {}
    if config['nordpool'].get('price_area') != price_area:
        config['nordpool']['price_area'] = price_area
        modified = True

# Update input sensors
if 'input_sensors' not in config:
    config['input_sensors'] = {}

if battery_soc and config['input_sensors'].get('battery_soc') != battery_soc:
    config['input_sensors']['battery_soc'] = battery_soc
    modified = True
if pv_sensor and config['input_sensors'].get('total_pv_production') != pv_sensor:
    config['input_sensors']['total_pv_production'] = pv_sensor
    modified = True
if load_sensor and config['input_sensors'].get('total_load_consumption') != load_sensor:
    config['input_sensors']['total_load_consumption'] = load_sensor
    modified = True

# Update system profile
if 'system' not in config:
    config['system'] = {}

if config['system'].get('has_solar') != has_solar:
    config['system']['has_solar'] = has_solar
    modified = True
if config['system'].get('has_battery') != has_battery:
    config['system']['has_battery'] = has_battery
    modified = True
if config['system'].get('has_water_heater') != has_water_heater:
    config['system']['has_water_heater'] = has_water_heater
    modified = True

if modified:
    with open(config_path, 'w') as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)
    print("[run.sh] Applied Add-on settings to config.yaml")
else:
    print("[run.sh] Config unchanged")
EOF

# Symlink config files to app directory
ln -sf /config/darkstar/config.yaml /app/config.yaml
ln -sf /config/darkstar/secrets.yaml /app/secrets.yaml

# Create data directory for persistent storage
mkdir -p /share/darkstar
ln -sf /share/darkstar /app/data

log "=========================================="
log "  Darkstar Energy Manager v2.2.0"
log "=========================================="
log "  Timezone: $TIMEZONE"
log "  Log Level: $LOG_LEVEL"
log "  Price Area: $PRICE_AREA"
log "  Has Solar: $HAS_SOLAR"
log "  Has Battery: $HAS_BATTERY"
log "  Has Water Heater: $HAS_WATER_HEATER"
if [ -n "$SUPERVISOR_TOKEN" ]; then
    log "  HA Auth: Supervisor Token (auto)"
else
    log "  HA Auth: Manual token (secrets.yaml)"
fi
log "  Web UI: http://localhost:5000"
log "=========================================="

# Start Flask
exec python3 -m flask run --host=0.0.0.0 --port=5000
