#!/usr/bin/env bash
# Darkstar Energy Manager - Home Assistant Add-on Entrypoint
set -e

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# Read options from HA Add-on config
CONFIG_PATH=/data/options.json

if [ -f "$CONFIG_PATH" ]; then
    TIMEZONE=$(jq -r '.timezone // "Europe/Stockholm"' "$CONFIG_PATH")
    LOG_LEVEL=$(jq -r '.log_level // "info"' "$CONFIG_PATH")
    PRICE_AREA=$(jq -r '.price_area // "SE4"' "$CONFIG_PATH")
    
    # Entity selections from Add-on UI
    BATTERY_SOC=$(jq -r '.battery_soc_sensor // ""' "$CONFIG_PATH")
    PV_SENSOR=$(jq -r '.pv_production_sensor // ""' "$CONFIG_PATH")
    LOAD_SENSOR=$(jq -r '.load_consumption_sensor // ""' "$CONFIG_PATH")
    
    # System profile toggles
    HAS_SOLAR=$(jq -r '.has_solar // true' "$CONFIG_PATH")
    HAS_BATTERY=$(jq -r '.has_battery // true' "$CONFIG_PATH")
    HAS_WATER_HEATER=$(jq -r '.has_water_heater // true' "$CONFIG_PATH")
else
    TIMEZONE="Europe/Stockholm"
    LOG_LEVEL="info"
    PRICE_AREA="SE4"
    BATTERY_SOC=""
    PV_SENSOR=""
    LOAD_SENSOR=""
    HAS_SOLAR="true"
    HAS_BATTERY="true"
    HAS_WATER_HEATER="true"
fi

# Set timezone
export TZ="$TIMEZONE"
export LOG_LEVEL="$LOG_LEVEL"

# Create config directory
mkdir -p /config/darkstar

# =============================================================================
# AUTO-DETECT HA CONNECTION (SUPERVISOR_TOKEN)
# =============================================================================
# When running as HA Add-on, SUPERVISOR_TOKEN is automatically available
# and we can use http://supervisor/core as the HA API endpoint

if [ -n "$SUPERVISOR_TOKEN" ]; then
    log "HA Add-on detected - auto-configuring connection..."
    
    # Generate secrets.yaml with Supervisor token (no manual token needed!)
    cat > /config/darkstar/secrets.yaml << EOF
# Auto-generated by Darkstar HA Add-on
# Using SUPERVISOR_TOKEN for automatic HA authentication
home_assistant:
  url: "http://supervisor/core"
  token: "${SUPERVISOR_TOKEN}"

notifications:
  discord_webhook_url: ""
EOF
    log "Generated secrets.yaml with Supervisor token"
else
    # Standalone mode - copy template if missing
    if [ ! -f /config/darkstar/secrets.yaml ]; then
        cp /app/secrets.example.yaml /config/darkstar/secrets.yaml
        log "Created secrets template at /config/darkstar/secrets.yaml"
        log "Please edit /config/darkstar/secrets.yaml with your HA token!"
    fi
fi

# =============================================================================
# CONFIG.YAML SETUP
# =============================================================================

if [ ! -f /config/darkstar/config.yaml ]; then
    cp /app/config.default.yaml /config/darkstar/config.yaml
    log "Created default config at /config/darkstar/config.yaml"
fi

# Apply Add-on UI settings to config.yaml
python3 << EOF
import sys
import os
import json
from pathlib import Path

# Try to import ruamel.yaml for comment preservation, fallback to PyYAML
try:
    from ruamel.yaml import YAML
    yaml = YAML()
    yaml.preserve_quotes = True
    HAS_RUAMEL = True
    print("[run.sh] Using ruamel.yaml (comments preserved)")
except ImportError:
    import yaml
    HAS_RUAMEL = False
    print("[run.sh] Using PyYAML (comments NOT preserved)")

def safe_load_stream(stream):
    if HAS_RUAMEL:
        return yaml.load(stream)
    else:
        return yaml.safe_load(stream) or {}

def safe_dump_stream(data, stream):
    if HAS_RUAMEL:
        yaml.dump(data, stream)
    else:
        yaml.dump(data, stream, default_flow_style=False, sort_keys=False)

config_path = Path('/config/darkstar/config.yaml')
secrets_path = Path('/config/darkstar/secrets.yaml')

# Load existing files
try:
    if config_path.exists():
        with open(config_path) as f:
            config = safe_load_stream(f)
    else:
        config = {}
except Exception as e:
    print(f"[run.sh] Error loading config.yaml: {e}")
    config = {}

try:
    if secrets_path.exists():
        with open(secrets_path) as f:
            secrets = safe_load_stream(f)
    else:
        secrets = {}
except Exception as e:
    print(f"[run.sh] Error loading secrets.yaml: {e}")
    secrets = {}

modified_config = False
modified_secrets = False

# -----------------------------------------------------------------------------
# HA CONNECTION (SECRETS)
# -----------------------------------------------------------------------------
supervisor_token = os.environ.get('SUPERVISOR_TOKEN')
if supervisor_token:
    if 'home_assistant' not in secrets:
        secrets['home_assistant'] = {}
    
    # Always update token (it rotates)
    if secrets['home_assistant'].get('token') != supervisor_token:
        secrets['home_assistant']['token'] = supervisor_token
        modified_secrets = True
    
    # Only set URL if missing (don't overwrite manual changes)
    if not secrets['home_assistant'].get('url'):
        secrets['home_assistant']['url'] = "http://supervisor/core"
        modified_secrets = True

# -----------------------------------------------------------------------------
# ADD-ON CONFIGURATION
# -----------------------------------------------------------------------------
# Read options.json directly to avoid "default overwrite" issues
options_path = Path('/data/options.json')
options = {}
if options_path.exists():
    try:
        options = json.loads(options_path.read_text())
    except Exception as e:
        print(f"[run.sh] Error reading options.json: {e}")

# Apply settings ONLY if they exist in options.json (user configured them)
def update_config(section, key, value, transform=None):
    global modified_config
    if value is None or value == "":
        return
    
    if transform:
        try:
            value = transform(value)
        except:
            return

    if section not in config:
        config[section] = {}
    
    if config[section].get(key) != value:
        print(f"[run.sh] Updating {section}.{key} from Add-on Config: {value}")
        config[section][key] = value
        modified_config = True

# 1. Price Area
if 'price_area' in options:
    update_config('nordpool', 'price_area', options['price_area'])

# 2. Timezone
if 'timezone' in options:
    if config.get('timezone') != options['timezone']:
        config['timezone'] = options['timezone']
        modified_config = True

# 3. Input Sensors
if 'battery_soc_sensor' in options:
    update_config('input_sensors', 'battery_soc', options['battery_soc_sensor'])

if 'pv_production_sensor' in options:
    update_config('input_sensors', 'total_pv_production', options['pv_production_sensor'])

if 'load_consumption_sensor' in options:
    update_config('input_sensors', 'total_load_consumption', options['load_consumption_sensor'])

# 4. System Toggles
if 'has_solar' in options:
    update_config('system', 'has_solar', options['has_solar'], lambda x: bool(x))

if 'has_battery' in options:
    update_config('system', 'has_battery', options['has_battery'], lambda x: bool(x))

if 'has_water_heater' in options:
    update_config('system', 'has_water_heater', options['has_water_heater'], lambda x: bool(x))


if modified_config:
    with open(config_path, 'w') as f:
        safe_dump_stream(config, f)
    print("[run.sh] Applied Add-on settings to config.yaml")
else:
    print("[run.sh] Config unchanged")

if modified_secrets:
    with open(secrets_path, 'w') as f:
        safe_dump_stream(secrets, f)
    print("[run.sh] Updated secrets.yaml")
else:
    print("[run.sh] Secrets unchanged")

EOF

# Symlink config files to app directory
ln -sf /config/darkstar/config.yaml /app/config.yaml
ln -sf /config/darkstar/secrets.yaml /app/secrets.yaml

# Create data directory for persistent storage
mkdir -p /share/darkstar
ln -sf /share/darkstar /app/data

log "=========================================="
log "  Darkstar Energy Manager v2.4.19-beta"
log "=========================================="
log "  Timezone: $TIMEZONE"
log "  Log Level: $LOG_LEVEL"
log "  Price Area: $PRICE_AREA"
log "  Has Solar: $HAS_SOLAR"
log "  Has Battery: $HAS_BATTERY"
log "  Has Water Heater: $HAS_WATER_HEATER"
if [ -n "$SUPERVISOR_TOKEN" ]; then
    log "  HA Auth: Supervisor Token (auto)"
else
    log "  HA Auth: Manual token (secrets.yaml)"
fi
log "  Web UI: http://localhost:5000"
log "=========================================="

# Start FastAPI via Uvicorn
exec uvicorn backend.main:app --host 0.0.0.0 --port 5000 --log-level "$LOG_LEVEL"
