from typing import Any

class LpConstraint: ...

class LpAffineExpression:
    def __add__(self, other: Any) -> LpAffineExpression: ...
    def __radd__(self, other: Any) -> LpAffineExpression: ...
    def __sub__(self, other: Any) -> LpAffineExpression: ...
    def __rsub__(self, other: Any) -> LpAffineExpression: ...
    def __mul__(self, other: float | int) -> LpAffineExpression: ...
    def __rmul__(self, other: float | int) -> LpAffineExpression: ...
    def __neg__(self) -> LpAffineExpression: ...
    def __le__(self, other: Any) -> LpConstraint: ...
    def __ge__(self, other: Any) -> LpConstraint: ...
    def __eq__(self, other: Any) -> LpConstraint: ...  # type: ignore[override]

class LpVariable:
    varValue: float | None
    def __init__(
        self,
        name: str,
        lowBound: float | None = ...,
        upBound: float | None = ...,
        cat: str = ...,
    ) -> None: ...
    @classmethod
    def dicts(
        cls,
        name: str,
        indices: Any,
        lowBound: float | None = ...,
        upBound: float | None = ...,
        cat: str = ...,
    ) -> dict[Any, LpVariable]: ...
    def __add__(self, other: Any) -> LpAffineExpression: ...
    def __radd__(self, other: Any) -> LpAffineExpression: ...
    def __sub__(self, other: Any) -> LpAffineExpression: ...
    def __rsub__(self, other: Any) -> LpAffineExpression: ...
    def __mul__(self, other: float | int) -> LpAffineExpression: ...
    def __rmul__(self, other: float | int) -> LpAffineExpression: ...
    def __neg__(self) -> LpAffineExpression: ...
    def __le__(self, other: Any) -> LpConstraint: ...
    def __ge__(self, other: Any) -> LpConstraint: ...
    def __eq__(self, other: Any) -> LpConstraint: ...  # type: ignore[override]

class LpProblem:
    constraints: dict[str, LpConstraint]
    def __init__(self, name: str = ..., sense: int = ...) -> None: ...
    def solve(self, solver: Any = ...) -> int: ...
    @property
    def status(self) -> int: ...
    @property
    def objective(self) -> LpAffineExpression: ...
    def variables(self) -> list[LpVariable]: ...
    def __iadd__(self, other: LpConstraint | LpAffineExpression | tuple[Any, str]) -> LpProblem: ...
    def writeLP(self, filename: str) -> None: ...

class GLPK_CMD:
    def __init__(
        self, msg: bool = ..., timeLimit: int | None = ..., options: list[str] = ...
    ) -> None: ...

class PULP_CBC_CMD:
    def __init__(
        self, msg: bool = ..., timeLimit: int | None = ..., threads: int | None = ...
    ) -> None: ...

LpMinimize: int
LpMaximize: int
LpStatus: dict[int, str]
LpStatusOptimal: int
LpContinuous: str
LpInteger: str
LpBinary: str

def lpSum(vector: Any) -> LpAffineExpression: ...
def value(var: LpVariable | LpAffineExpression | None) -> float | None: ...
