#!/usr/bin/env bash
# Darkstar Energy Manager - Home Assistant Add-on Entrypoint
set -e

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# Read options from HA Add-on config
CONFIG_PATH=/data/options.json

if [ -f "$CONFIG_PATH" ]; then
    TIMEZONE=$(jq -r '.timezone // "Europe/Stockholm"' "$CONFIG_PATH")
    LOG_LEVEL=$(jq -r '.log_level // "info"' "$CONFIG_PATH")
    PRICE_AREA=$(jq -r '.price_area // "SE4"' "$CONFIG_PATH")
else
    TIMEZONE="Europe/Stockholm"
    LOG_LEVEL="info"
    PRICE_AREA="SE4"
fi

# Set timezone
export TZ="$TIMEZONE"
export LOG_LEVEL="$LOG_LEVEL"

# Create config directory
mkdir -p /config/darkstar

# =============================================================================
# AUTO-DETECT HA CONNECTION (SUPERVISOR_TOKEN)
# =============================================================================
# When running as HA Add-on, SUPERVISOR_TOKEN is automatically available
# and we can use http://supervisor/core as the HA API endpoint

if [ -n "$SUPERVISOR_TOKEN" ]; then
    log "HA Add-on detected - auto-configuring connection..."

    # Generate secrets.yaml with Supervisor token (no manual token needed!)
    cat > /config/darkstar/secrets.yaml << EOF
# Auto-generated by Darkstar HA Add-on
# Using SUPERVISOR_TOKEN for automatic HA authentication
home_assistant:
  url: "http://supervisor/core"
  token: "${SUPERVISOR_TOKEN}"

notifications:
  discord_webhook_url: ""
EOF
    log "Generated secrets.yaml with Supervisor token"
else
    # Standalone mode - copy template if missing
    if [ ! -f /config/darkstar/secrets.yaml ]; then
        cp /app/secrets.example.yaml /config/darkstar/secrets.yaml
        log "Created secrets template at /config/darkstar/secrets.yaml"
        log "Please edit /config/darkstar/secrets.yaml with your HA token!"
    fi
fi

# =============================================================================
# CONFIG.YAML SETUP
# =============================================================================

if [ ! -f /config/darkstar/config.yaml ]; then
    cp /app/config.default.yaml /config/darkstar/config.yaml
    log "Created default config at /config/darkstar/config.yaml"
fi

# Apply Add-on UI settings to config.yaml
python3 << EOF
import sys
import os
import json
import asyncio
from pathlib import Path

# Try to import ruamel.yaml for comment preservation
try:
    from ruamel.yaml import YAML
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.width = 4096  # Prevent wrapping of long entity IDs (REV F16)
    HAS_RUAMEL = True
    print("[run.sh] Using ruamel.yaml (comments preserved)")
except ImportError:
    # REV F16: Removed PyYAML fallback to prevent comment wiping
    print("[run.sh] CRITICAL ERROR: ruamel.yaml not found!")
    print("[run.sh] Config comments cannot be preserved without ruamel.yaml.")
    print("[run.sh] Please ensure 'ruamel.yaml' is installed in the system environment.")
    # We exit here to force a fix rather than silently corrupting config
    sys.exit(1)

# REV F58: Import proper config migration (Phase 1)
sys.path.insert(0, '/app')
try:
    from backend.config_migration import migrate_config
    HAS_MIGRATION = True
except ImportError as e:
    print(f"[run.sh] Warning: Could not import migrate_config: {e}")
    print("[run.sh] Will fall back to legacy merge logic")
    HAS_MIGRATION = False

def safe_load_stream(stream):
    return yaml.load(stream)

def safe_dump_stream(data, stream):
    yaml.dump(data, stream)

config_path = Path('/config/darkstar/config.yaml')
default_config_path = Path('/app/config.default.yaml')
secrets_path = Path('/config/darkstar/secrets.yaml')

# Load existing files
try:
    if config_path.exists():
        with open(config_path) as f:
            config = safe_load_stream(f)
    else:
        config = {}
except Exception as e:
    print(f"[run.sh] Error loading config.yaml: {e}")
    config = {}

# Load defaults for migration (REV F17)
try:
    if default_config_path.exists():
        with open(default_config_path) as f:
            default_config = safe_load_stream(f)
    else:
        default_config = {}
except Exception as e:
    print(f"[run.sh] Warning: Could not load config.default.yaml for migration: {e}")
    default_config = {}

# REV F58: Replace deep_merge_missing with proper F57 migration (Phase 1)
# This ensures deprecated keys are removed and config structure is normalized
config_was_modified = False
if HAS_MIGRATION:
    try:
        print("[run.sh] Running proper config migration (REV F58)...")
        # Run the async migration function - it modifies the file directly
        asyncio.run(migrate_config(
            str(config_path),
            str(default_config_path),
            strict_validation=False
        ))
        # Migration succeeded, mark as modified and reload config
        config_was_modified = True
        print("[run.sh] ✓ Config migration completed successfully")
        # Reload the migrated config for the rest of the script
        try:
            with open(config_path) as f:
                config = safe_load_stream(f)
            print("[run.sh] Reloaded migrated config")
        except Exception as e:
            print(f"[run.sh] Warning: Failed to reload migrated config: {e}")
    except Exception as e:
        print(f"[run.sh] Warning: Migration failed: {e}")
        print("[run.sh] Will attempt legacy merge as fallback")
        # Fallback: use the old logic as a safety net
        HAS_MIGRATION = False

# Fallback for when migration is not available
if not HAS_MIGRATION:
    def deep_merge_missing(target, source):
        """Recursively add missing keys from source to target while preserving target values and comments."""
        is_modified = False
        if not isinstance(source, dict) or not isinstance(target, dict):
            return False

        for key, value in source.items():
            if key not in target:
                print(f"[run.sh] Migration: Adding missing key '{key}' to config.yaml")
                target[key] = value
                is_modified = True
            elif isinstance(value, dict) and isinstance(target.get(key), dict):
                if deep_merge_missing(target[key], value):
                    is_modified = True
        return is_modified

    config_was_modified = deep_merge_missing(config, default_config)

try:
    if secrets_path.exists():
        with open(secrets_path) as f:
            secrets = safe_load_stream(f)
    else:
        secrets = {}
except Exception as e:
    print(f"[run.sh] Error loading secrets.yaml: {e}")
    secrets = {}

modified_config = config_was_modified
modified_secrets = False

# -----------------------------------------------------------------------------
# HA CONNECTION (SECRETS)
# -----------------------------------------------------------------------------
supervisor_token = os.environ.get('SUPERVISOR_TOKEN')
if supervisor_token:
    if 'home_assistant' not in secrets:
        secrets['home_assistant'] = {}

    # Always update token (it rotates)
    if secrets['home_assistant'].get('token') != supervisor_token:
        secrets['home_assistant']['token'] = supervisor_token
        modified_secrets = True

    # Only set URL if missing (don't overwrite manual changes)
    if not secrets['home_assistant'].get('url'):
        secrets['home_assistant']['url'] = "http://supervisor/core"
        modified_secrets = True

# -----------------------------------------------------------------------------
# ADD-ON CONFIGURATION
# -----------------------------------------------------------------------------
# Read options.json directly to avoid "default overwrite" issues
options_path = Path('/data/options.json')
options = {}
if options_path.exists():
    try:
        options = json.loads(options_path.read_text())
    except Exception as e:
        print(f"[run.sh] Error reading options.json: {e}")

# Apply settings ONLY if they exist in options.json (user configured them)
def update_config(section, key, value, transform=None):
    global modified_config
    if value is None or value == "":
        return

    if transform:
        try:
            value = transform(value)
        except:
            return

    if section not in config:
        config[section] = {}

    if config[section].get(key) != value:
        print(f"[run.sh] Updating {section}.{key} from Add-on Config: {value}")
        config[section][key] = value
        modified_config = True

# 1. Price Area
if 'price_area' in options:
    update_config('nordpool', 'price_area', options['price_area'])

# 2. Timezone
if 'timezone' in options:
    if config.get('timezone') != options['timezone']:
        config['timezone'] = options['timezone']
        modified_config = True

# 3. Input Sensors
if 'battery_soc_sensor' in options:
    update_config('input_sensors', 'battery_soc', options['battery_soc_sensor'])

# 4. System Toggles
if 'has_solar' in options:
    update_config('system', 'has_solar', options['has_solar'], lambda x: bool(x))

if 'has_battery' in options:
    update_config('system', 'has_battery', options['has_battery'], lambda x: bool(x))

if 'has_water_heater' in options:
    update_config('system', 'has_water_heater', options['has_water_heater'], lambda x: bool(x))


if modified_secrets:
    with open(secrets_path, 'w') as f:
        safe_dump_stream(secrets, f)
    print("[run.sh] Updated secrets.yaml")

if modified_config:
    with open(config_path, 'w') as f:
        safe_dump_stream(config, f)
    print("[run.sh] Applied Add-on settings to config.yaml")

# -----------------------------------------------------------------------------
# FINAL STATUS LOGGING (SSOT: config.yaml)
# -----------------------------------------------------------------------------
import datetime
ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
prefix = f"[{ts}]"

app_version = open("/app/VERSION").read().strip() if os.path.exists("/app/VERSION") else "unknown"
print(f"{prefix} ==========================================")
print(f"{prefix}   Darkstar Energy Manager {app_version}")
print(f"{prefix} ==========================================")
print(f"{prefix}   Timezone:      {config.get('timezone', 'Europe/Stockholm')}")
print(f"{prefix}   Log Level:     {os.environ.get('LOG_LEVEL', 'info')}")
print(f"{prefix}   Price Area:    {config.get('nordpool', {}).get('price_area', 'SE4')}")

sys_cfg = config.get('system', {})
print(f"{prefix}   Has Solar:     {str(sys_cfg.get('has_solar', True)).lower()}")
print(f"{prefix}   Has Battery:   {str(sys_cfg.get('has_battery', True)).lower()}")
print(f"{prefix}   Has Water:     {str(sys_cfg.get('has_water_heater', True)).lower()}")

if supervisor_token:
    print(f"{prefix}   HA Auth:       Supervisor Token (auto)")
else:
    print(f"{prefix}   HA Auth:       Manual token (secrets.yaml)")

print(f"{prefix}   Web UI:        http://localhost:5000")
print(f"{prefix} ==========================================")
EOF

# Symlink config files to app directory
ln -sf /config/darkstar/config.yaml /app/config.yaml
ln -sf /config/darkstar/secrets.yaml /app/secrets.yaml

# Create data directory for persistent storage
mkdir -p /share/darkstar
ln -sf /share/darkstar /app/data



# -----------------------------------------------------------------------------
# DATABASE MIGRATION (ALEMBIC)
# -----------------------------------------------------------------------------
# Run Alembic migrations to ensure database schema is current.
# This prevents "no such column" errors when upgrading to versions with new schema.
log "Running database migrations..."
export DB_PATH=/share/darkstar/planner_learning.db

if [ -f /app/alembic.ini ]; then
    # Run migration with proper error handling and logging
    if /usr/local/bin/python3.12 -m alembic upgrade head 2>&1 | while read -r line; do log "[ALEMBIC] $line"; done; then
        log "✅ Database migrations complete."
    else
        log "❌ ERROR: Database migration failed!"
        log "Recovery: Check the logs above for detailed error information."
        log "The container will now exit to prevent starting with an inconsistent database state."
        exit 1
    fi
else
    log "⚠️  WARNING: /app/alembic.ini not found, skipping database migrations."
    log "HINT: This may cause errors if the database schema is outdated."
fi

# -----------------------------------------------------------------------------
# LEGACY CODE DETECTION (REV ARC11)
# -----------------------------------------------------------------------------
# Ensure we aren't accidentally running old sync code after the ARC11 migration
if grep -q "store.Session()" /app/backend/learning/store.py 2>/dev/null; then
    log "CRITICAL ERROR: Legacy sync code detected in store.py!"
    log "The ARC11 migration requires a clean async codebase."
    log "Please pull the latest changes and ensure 'store.Session' is removed."
    exit 1
fi

log "Bootstrapping complete. Starting server..."

# Start FastAPI via Uvicorn
exec uvicorn backend.main:app --host 0.0.0.0 --port 5000 --log-level "$LOG_LEVEL"
