from typing import Any

class Prices:
    def __init__(self, currency: str = ...): ...
    def hourly(self, areas: list[str] = ..., end_date: Any | None = ...) -> dict[str, Any]: ...
    def fetch(
        self, end_date: Any | None = ..., areas: list[str] = ..., resolution: int = ...
    ) -> dict[str, Any]: ...
