"""baseline

Revision ID: f6c8f45208da
Revises: 
Create Date: 2026-01-17 11:44:02.659754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c8f45208da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antares_policy_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('models_dir', sa.String(), nullable=False),
    sa.Column('target_names', sa.String(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('antares_rl_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('algo', sa.String(), nullable=False),
    sa.Column('state_version', sa.String(), nullable=False),
    sa.Column('action_version', sa.String(), nullable=False),
    sa.Column('train_start_date', sa.String(), nullable=True),
    sa.Column('train_end_date', sa.String(), nullable=True),
    sa.Column('val_start_date', sa.String(), nullable=True),
    sa.Column('val_end_date', sa.String(), nullable=True),
    sa.Column('hyperparams_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('artifact_dir', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('antares_training_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.Column('train_start_date', sa.String(), nullable=False),
    sa.Column('train_end_date', sa.String(), nullable=False),
    sa.Column('val_start_date', sa.String(), nullable=True),
    sa.Column('val_end_date', sa.String(), nullable=True),
    sa.Column('targets', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('hyperparams_json', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('artifact_dir', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('battery_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avg_cost_sek_per_kwh', sa.Float(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('yaml_blob', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_water',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('used_kwh', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('data_quality_daily',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('bad_hours_load', sa.Integer(), nullable=False),
    sa.Column('bad_hours_pv', sa.Integer(), nullable=False),
    sa.Column('bad_hours_import', sa.Integer(), nullable=False),
    sa.Column('bad_hours_export', sa.Integer(), nullable=False),
    sa.Column('bad_hours_batt', sa.Integer(), nullable=False),
    sa.Column('missing_slots', sa.Integer(), nullable=False),
    sa.Column('soc_issues', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('executed_at', sa.String(), nullable=False),
    sa.Column('slot_start', sa.String(), nullable=False),
    sa.Column('planned_charge_kw', sa.Float(), nullable=True),
    sa.Column('planned_discharge_kw', sa.Float(), nullable=True),
    sa.Column('planned_export_kw', sa.Float(), nullable=True),
    sa.Column('planned_water_kw', sa.Float(), nullable=True),
    sa.Column('planned_soc_target', sa.Integer(), nullable=True),
    sa.Column('planned_soc_projected', sa.Integer(), nullable=True),
    sa.Column('commanded_work_mode', sa.String(), nullable=True),
    sa.Column('commanded_grid_charging', sa.Integer(), nullable=True),
    sa.Column('commanded_charge_current_a', sa.Float(), nullable=True),
    sa.Column('commanded_discharge_current_a', sa.Float(), nullable=True),
    sa.Column('commanded_soc_target', sa.Integer(), nullable=True),
    sa.Column('commanded_water_temp', sa.Integer(), nullable=True),
    sa.Column('before_soc_percent', sa.Float(), nullable=True),
    sa.Column('before_work_mode', sa.String(), nullable=True),
    sa.Column('before_water_temp', sa.Float(), nullable=True),
    sa.Column('before_pv_kw', sa.Float(), nullable=True),
    sa.Column('before_load_kw', sa.Float(), nullable=True),
    sa.Column('override_active', sa.Integer(), nullable=False),
    sa.Column('override_type', sa.String(), nullable=True),
    sa.Column('override_reason', sa.String(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('executor_version', sa.String(), nullable=True),
    sa.Column('commanded_unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_log_executed_at'), 'execution_log', ['executed_at'], unique=False)
    op.create_index(op.f('ix_execution_log_slot_start'), 'execution_log', ['slot_start'], unique=False)
    op.create_table('learning_daily_metrics',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('pv_error_by_hour_kwh', sa.Text(), nullable=True),
    sa.Column('load_error_by_hour_kwh', sa.Text(), nullable=True),
    sa.Column('pv_adjustment_by_hour_kwh', sa.Text(), nullable=True),
    sa.Column('load_adjustment_by_hour_kwh', sa.Text(), nullable=True),
    sa.Column('soc_error_mean_pct', sa.Float(), nullable=True),
    sa.Column('soc_error_stddev_pct', sa.Float(), nullable=True),
    sa.Column('pv_error_mean_abs_kwh', sa.Float(), nullable=True),
    sa.Column('load_error_mean_abs_kwh', sa.Float(), nullable=True),
    sa.Column('s_index_base_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('learning_param_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('param_path', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('loop', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_metrics_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_debug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realized_energy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_start', sa.String(), nullable=False),
    sa.Column('slot_end', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflex_state',
    sa.Column('param_path', sa.String(), nullable=False),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('param_path')
    )
    op.create_table('schedule_planned',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('planned_kwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_planned_date'), 'schedule_planned', ['date'], unique=False)
    op.create_table('sensor_totals',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('last_timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('slot_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_start', sa.String(), nullable=False),
    sa.Column('pv_forecast_kwh', sa.Float(), nullable=False),
    sa.Column('load_forecast_kwh', sa.Float(), nullable=False),
    sa.Column('pv_p10', sa.Float(), nullable=True),
    sa.Column('pv_p90', sa.Float(), nullable=True),
    sa.Column('load_p10', sa.Float(), nullable=True),
    sa.Column('load_p90', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('forecast_version', sa.String(), nullable=False),
    sa.Column('pv_correction_kwh', sa.Float(), nullable=False),
    sa.Column('load_correction_kwh', sa.Float(), nullable=False),
    sa.Column('correction_source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_start', 'forecast_version')
    )
    op.create_table('slot_observations',
    sa.Column('slot_start', sa.String(), nullable=False),
    sa.Column('slot_end', sa.String(), nullable=False),
    sa.Column('import_kwh', sa.Float(), nullable=False),
    sa.Column('export_kwh', sa.Float(), nullable=False),
    sa.Column('pv_kwh', sa.Float(), nullable=False),
    sa.Column('load_kwh', sa.Float(), nullable=False),
    sa.Column('water_kwh', sa.Float(), nullable=False),
    sa.Column('batt_charge_kwh', sa.Float(), nullable=True),
    sa.Column('batt_discharge_kwh', sa.Float(), nullable=True),
    sa.Column('soc_start_percent', sa.Float(), nullable=True),
    sa.Column('soc_end_percent', sa.Float(), nullable=True),
    sa.Column('import_price_sek_kwh', sa.Float(), nullable=True),
    sa.Column('export_price_sek_kwh', sa.Float(), nullable=True),
    sa.Column('executed_action', sa.String(), nullable=True),
    sa.Column('quality_flags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('slot_start')
    )
    op.create_table('slot_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_start', sa.String(), nullable=False),
    sa.Column('planned_charge_kwh', sa.Float(), nullable=True),
    sa.Column('planned_discharge_kwh', sa.Float(), nullable=True),
    sa.Column('planned_soc_percent', sa.Float(), nullable=True),
    sa.Column('planned_import_kwh', sa.Float(), nullable=True),
    sa.Column('planned_export_kwh', sa.Float(), nullable=True),
    sa.Column('planned_water_heating_kwh', sa.Float(), nullable=True),
    sa.Column('planned_cost_sek', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_start')
    )
    op.create_table('strategy_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('overrides_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_episodes',
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('schedule_json', sa.Text(), nullable=False),
    sa.Column('config_overrides_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_table('vacation_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacation_state')
    op.drop_table('training_episodes')
    op.drop_table('strategy_log')
    op.drop_table('slot_plans')
    op.drop_table('slot_observations')
    op.drop_table('slot_forecasts')
    op.drop_table('sensor_totals')
    op.drop_index(op.f('ix_schedule_planned_date'), table_name='schedule_planned')
    op.drop_table('schedule_planned')
    op.drop_table('reflex_state')
    op.drop_table('realized_energy')
    op.drop_table('planner_debug')
    op.drop_table('learning_runs')
    op.drop_table('learning_param_history')
    op.drop_table('learning_daily_metrics')
    op.drop_index(op.f('ix_execution_log_slot_start'), table_name='execution_log')
    op.drop_index(op.f('ix_execution_log_executed_at'), table_name='execution_log')
    op.drop_table('execution_log')
    op.drop_table('data_quality_daily')
    op.drop_table('daily_water')
    op.drop_table('config_versions')
    op.drop_table('battery_cost')
    op.drop_table('antares_training_runs')
    op.drop_table('antares_rl_runs')
    op.drop_table('antares_policy_runs')
    # ### end Alembic commands ###
