from collections.abc import Callable
from typing import Any

class SocketIO:
    def __init__(self, app: Any = ..., cors_allowed_origins: Any = ..., **kwargs: Any): ...
    def init_app(self, app: Any, **kwargs: Any): ...
    def run(self, app: Any, **kwargs: Any): ...
    def stop(self): ...
    def emit(self, event: str, data: Any = ..., **kwargs: Any): ...
    def on(self, event: str, namespace: str | None = ...) -> Callable: ...
